version: 2
orbs:
  heroku: circleci/heroku@1.0.1 
jobs:
  build:
    working_directory: ~/sudoku
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: mkdir build_artifacts
      - run: pipenv run flake8 > build_artifacts/flake8.txt
      - run: pipenv run radon cc sudoku -a > build_artifacts/radon.txt
      - run: pipenv run pytest

      - store_test_results:
          path: build_artifacts/test_results

      - store_artifacts:
          path: /home/circleci/sudoku/build_artifacts/
          destination: build_artifacts
  deploy: 
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git