version: 2.1

jobs:
  build:
    working_directory: ~/sudoku
    docker:
      - image: circleci/python:3.8.2
    steps:
      - run:
        command: |
          sudo pip install pipenv
          pipenv install --dev
      - run:
        command: |
          pipenv run pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
