version: 2

jobs:
  build:
    working_directory: ~/sudoku
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pytest
      - store_test_results:
          path: test-results
